# generated by datamodel-codegen:
#   filename:  contact.json
#   timestamp: 2023-10-28T13:53:14+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import RootModel

from . import MoneybirdBaseModel


class Note(MoneybirdBaseModel):
    id: str
    administration_id: str
    entity_id: str
    entity_type: str
    user_id: str
    assignee_id: Optional[str] = None
    todo: bool
    note: str
    completed_at: None
    completed_by_id: None
    todo_type: None
    data: Dict[str, Any]
    created_at: str
    updated_at: str


class CustomField(MoneybirdBaseModel):
    id: str
    name: str
    value: str


class ContactPerson(MoneybirdBaseModel):
    id: str
    contact_id: str
    administration_id: str
    firstname: str
    lastname: str
    phone: Optional[str] = None
    email: Optional[str] = None
    department: Optional[str] = None
    created_at: str
    updated_at: str
    version: int


class Event(MoneybirdBaseModel):
    administration_id: str
    user_id: str
    action: str
    link_entity_id: None
    link_entity_type: None
    data: Dict[str, Any]
    created_at: str
    updated_at: str


class Contact(MoneybirdBaseModel):
    id: str
    administration_id: str
    company_name: str
    firstname: str
    lastname: str
    address1: str
    address2: str
    zipcode: str
    city: str
    country: str
    phone: str
    delivery_method: str
    customer_id: str
    tax_number: str
    chamber_of_commerce: str
    bank_account: str
    attention: str
    email: str
    email_ubl: bool
    send_invoices_to_attention: str
    send_invoices_to_email: str
    send_estimates_to_attention: str
    send_estimates_to_email: str
    sepa_active: bool
    sepa_iban: str
    sepa_iban_account_name: str
    sepa_bic: str
    sepa_mandate_id: str
    sepa_mandate_date: None
    sepa_sequence_type: str
    credit_card_number: str
    credit_card_reference: str
    credit_card_type: None
    tax_number_validated_at: None
    tax_number_valid: None
    invoice_workflow_id: Optional[str]
    estimate_workflow_id: Optional[str]
    si_identifier: str
    si_identifier_type: None
    moneybird_payments_mandate: bool
    created_at: str
    updated_at: str
    version: int
    sales_invoices_url: str
    notes: List[Note]
    custom_fields: List[CustomField]
    contact_people: List[ContactPerson]
    archived: bool
    events: List[Event]


class ContactList(RootModel[List[Contact]]):
    root: List[Contact]

    def __len__(self) -> int:
        return len(self.root)
